version: '3'
services:
  server:
    build: message_service/
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:avitopass@composepostgres:5432/avitomes
  postgres:
    container_name: composepostgres
    build: db/
    volumes:
      - ./data:/var/lib/postgresql/data
  docs:
    container_name: raml
    image: gcr.io/api-console-a6952/app:0.1.0
    ports:
      - "8080:8080"
    volumes:
      - ./message_service/docs:/app/api
    environment:
      - API_PROJECT=avito-message.raml
      - API_TYPE=RAML 1.0
      - API_MIME=application/raml
